# Generated by Django 4.2.3 on 2023-09-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cpmment',
            new_name='comment',
        ),
    ]
